[package]
name = "codeowners-cli"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]
edition = "2018"

[[bin]]
name = "codeowners"
path = "src/main.rs"

[dependencies]
codeowners = { version = "0.1.0", path = "../lib" }
structopt = "0.2"
